// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"crypto/tls"
	"github.com/rishusahu23/fam-youtube/youtube"
	"net/http"
)

// Injectors from wire.go:

func InitialiseYoutubeService() *youtube.Service {
	service := youtube.NewService()
	return service
}

// wire.go:

func getHttpClient() *http.Client {
	return &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
	}
}
