// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"crypto/tls"
	"github.com/rishusahu23/fam-youtube/config"
	"github.com/rishusahu23/fam-youtube/external/ohttp"
	youtube2 "github.com/rishusahu23/fam-youtube/external/youtube"
	"github.com/rishusahu23/fam-youtube/youtube"
	"github.com/rishusahu23/fam-youtube/youtube/dao"
	"gorm.io/gorm"
	"net/http"
)

// Injectors from wire.go:

func InitialiseYoutubeService(conf *config.Config, db *gorm.DB) *youtube.Service {
	client := getHttpClient()
	httpRequestHandler := ohttp.NewHttpRequestHandler(client)
	clientImpl := youtube2.NewYoutubeClientImpl(httpRequestHandler, conf)
	youtubeClient := youtubeProvider(clientImpl)
	recordDaoImpl := dao.NewRecordDaoImpl(db)
	service := youtube.NewService(youtubeClient, recordDaoImpl)
	return service
}

// wire.go:

func getHttpClient() *http.Client {
	return &http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		},
	}
}

func youtubeProvider(impl *youtube2.ClientImpl) youtube2.Client {
	return impl
}

func httpHandlerProvider(impl *ohttp.HttpRequestHandler) ohttp.IHttpRequestHandler {
	return impl
}
