Server:
  Port: 8150
  # use 9090 port to test both grpc and http api
  GrpcPort: 9090
  GrpcHttpPort: 9091

PostgresConfig:
  Host: "fam-youtube-postgres-1"
  Port: 5432
  User: "root"
  Password: "root"
  DBName: "youtube"

# add api keys before server start
ApiKeys: []